### PR TITLE
Modified to allow header title builder

### PR DESCRIPTION
**Pull request by lohanidamodar**
Hi,
I was integrating table calendar in one of my plugins. And I wanted to customize the header title beyond what the styles supported. So I added this titleBuilder in HeaderStyle, using which user can complete use their own widget in title instead of default text.

If you think it might be useful for others too and is good, you can accept this PR.

If you have any issues or problems regarding this PR, feel free to contact.

### CODE REVIEW

**Comment by aleksanderwozniak** [comment]
Hi Damodar,

I totally get the idea behind this builder. One thing I'm thinking, is whether it would make more sense to add a separate custom header at this point - something like [this](https://gist.github.com/aleksanderwozniak/bcc6ce5c2a341f778de32a9bf8e16dd1), as it would be just way more flexible in design.

**Comment by lohanidamodar** [comment]
@aleksanderwozniak I'm sure that makes sense too, but for beginners it will be easier with builder as it follows the regular patterns with flutter and even table calendar itself has many builders.

**Comment by aleksanderwozniak** [comment]
Hmm I guess it will be a bit easier to use. In that case - let me know if you are willing to adapt it to v3, since it has modified internals (I will point you to a proper branch in the next comment).

Let's also put `titleBuilder` above the header's `GestureDetector`, as this will give users more control over its behavior.

**Comment by lohanidamodar** [comment]
Sure let me know the details

**Comment by aleksanderwozniak** [comment]
Perfect! 

You can use `3.0.0-beta` branch both as base and target branch. I think it will be the cleanest if you just open a new PR with this feature. 

Regarding implementation details: let's name it `headerTitleBuilder`, give it a `DayBuilder` typedef and put it inside `CalendarBuilders`. Feel free to ask if you have any further questions.

**Comment by aleksanderwozniak** [comment]
Hey Damodar, are there any updates on this PR? I will be migrating `3.0.0-beta` to null safety, so it would be best to merge this PR before that happens.

Alternatively this could be merged afterwards in null-safe style, to prevent migrating twice.

**Comment by lohanidamodar** [comment]
Hey @aleksanderwozniak I'll have the update today, is it ok?

**Comment by aleksanderwozniak** [comment]
Sure, go ahead.

**Comment by lohanidamodar** [comment]
@aleksanderwozniak check #400

**Comment by aleksanderwozniak** [comment]
Continued in #400.

**Pull request closed without merging**
