### PR TITLE
range select added

### LINKED ISSUE #119: Date Range Picker
Hi,
Can you add a feature in this library selecting the date range. Ex selecting dates from 2 to 25 in a particular month to see all the events which are between 2 and 25.
Thanks.

### PR DESCRIPTION
**Pull request by serendipity1004**
added range select functionality and styling

need to work on bits and pieces like events but currently can use callback to draw out your own.

Fixes #119

### CODE REVIEW

**Comment by serendipity1004** [comment]
we can do things like below now


Simulator Screen Shot - iPhone 12 Pro - 2021-01-13 at 15 24 25

**Comment by serendipity1004** [comment]
example code

``dart
void _onRangeSelected(List<DateTime> range, List events, List holidays){
    print(range[0]);
    print(range[1]);

  }

  // Simple TableCalendar configuration (using Styles)
  Widget _buildTableCalendar() {

    return TableCalendar(
      calendarController: _calendarController,
      selectRange: true,
      events: _events,
      holidays: _holidays,
      startingDayOfWeek: StartingDayOfWeek.monday,
      calendarStyle: CalendarStyle(
        selectedColor: Colors.deepOrange[400],
        todayColor: Colors.deepOrange[200],
        markersColor: Colors.brown[700],
        outsideDaysVisible: false,
        highlightToday: false,
        rangeStartDayColor: Color(0xFFf29061),
        rangeEndDayColor: Color(0xFFf29061),
        withinRangeDayColor: Color(0xFFf29061).withOpacity(0.24),
        rangeStartDayStyle: TextStyle(
          color: Colors.white,
        ),
        rangeEndDayStyle: TextStyle(
          color: Colors.white,
        ),
        withinRangeDayStyle: TextStyle(
          color: Colors.black,
        ),
      ),
      headerStyle: HeaderStyle(
        formatButtonTextStyle:
            TextStyle().copyWith(color: Colors.white, fontSize: 15.0),
        formatButtonDecoration: BoxDecoration(
          color: Colors.deepOrange[400],
          borderRadius: BorderRadius.circular(16.0),
        ),
      ),
      onRangeSelected: _onRangeSelected,
      onDaySelected: _onDaySelected,
      onVisibleDaysChanged: _onVisibleDaysChanged,
      onCalendarCreated: _onCalendarCreated,
    );
  }
```

**Comment by aleksanderwozniak** [comment]
Hi,
I will be publishing v3.0.0 soon, which changes a lot of internal code - thus requiring this PR to be basically rebuilt from scratch. Let me know if you are willing to reimplement it, otherwise I'll just add the code there myself.

**Comment by aleksanderwozniak** [comment]
I've added range selection to the updated internals - therefore closing this.

**Pull request closed without merging**
