### PR TITLE
feat: cell day localization

### PR DESCRIPTION
**Pull request by michaelsoliman1**
cell text is not localized, current:
```
    final text = '${day.day}';
```
now:
```
    final text = DateFormat.d(locale).format(day);
```

### CODE REVIEW

**Review by aleksanderwozniak — APPROVED** [review]
Thanks for contributing!

**Comment by synstin** [comment]
@michaelsoliman1 @aleksanderwozniak I specified the locale but don't want the cell day to show, is there a way to not expose it like in the old version?

**Comment by alvminvm** [comment]
I don't this feat. When the locale is set to "zh_CN", it show "28日" instead of "28". I want it to be displayed as numbers only

**Comment by michaelsoliman1** [comment]
Hello @synstin @alvminvm, I created this [pr](https://github.com/aleksanderwozniak/table_calendar/pull/879) that allows you to use different locale for days.

**Pull request merged**
