### PR TITLE
Feature/set today icon

### PR DESCRIPTION
**Pull request by jdeltoft**
This gives the user the option to turn on a "go to today" button in the header, between the current month/year and format button.

### CODE REVIEW

**Comment by hanyska** [comment]
Hello. Can you add _todayButtonVisible_?

**Comment by jdeltoft** [comment]
@aleksanderwozniak  Any desire to merge in a change like this?  Just curious. Let me know

**Comment by aleksanderwozniak** [comment]
@jdeltoft 
Hmm I'm leaning towards having this as something left for package user to add (perhaps to a [custom header](https://gist.github.com/aleksanderwozniak/bcc6ce5c2a341f778de32a9bf8e16dd1)), since it will be tough to customize to individual designs. Something like `todayButtonBuilder` could be added to support better customization, but at this point it seems very natural to just go with a custom header - to get everything tailored to the design.

One of the ways of implementing "go to today" functionality without making a custom header, is to add it to `onHeaderTapped` callback. This of course doesn't have the visual clue like an icon would, but it still feels intuitive and doesn't change the UI.

**Comment by aleksanderwozniak** [comment]
Actually, changes in v3.0.0 make this very impractical to add, since the button would have to expose a callback allowing `focusedDay` to be updated in the parent widget. It is much more natural to add such button manually in parent widget, as the callback would be right there.

There is also a new builder called `titleHeaderBuilder` which can also be used for such a button, essentially improving upon the aforementioned idea of `todayButtonBuilder`. This is a completely viable alternative to making a custom header for this.

Closing as a result of above.

**Pull request closed without merging**
