### PR TITLE
events marker count is a wrong number, fix it

### PR DESCRIPTION
**Pull request by riclava**

### CODE REVIEW

**Comment by MarceloRab** [comment]
events marker count is a wrong number, fix it. ==> Maximum 4 events

**Comment by ferrarafer** [comment]
Is this going to be fixed? I can confirm the events marker wrong number. Maximum 4 events.

**Comment by aleksanderwozniak** [comment]
This fixes a non-existent issue. Instead, you should use `markersMaxAmount` property (which defaults to 4):

```dart
calendarStyle: CalendarStyle(
  markersMaxAmount: 10,
),
```

**Comment by ferrarafer** [comment]
> ```dart
> markersMaxAmount: 10,
> ```

OK thanks. I didn't see the markersMaxAmount property. But, as much as I look for it, I find no reason for the default value to be 4, it should be null.
Thanks for this great package !!

**Comment by aleksanderwozniak** [comment]
It is set to 4 by default, because it is also used by single markers, and having more than 4 of those seems too crowded to me.

However, originally this property was used **only** by single markers. And I come to conclusion that it should have stayed that way - therefore, I will be making an update, where `markersMaxAmount` has no impact on `markersBuilder`. It will have no 'max limit' then.

**Pull request closed without merging**
